"""GenerateCompletionUseCase: Pure use case generating shell autocomplete definitions."""
from __future__ import annotations


class GenerateCompletionUseCase:
    """Generates shell autocomplete scripts for bash, zsh, and fish."""

    SUPPORTED_SHELLS = ("bash", "zsh", "fish")

    def execute(self, shell: str) -> str:
        shell_norm = shell.lower().strip()
        if shell_norm == "zsh":
            return self._generate_zsh()
        elif shell_norm == "bash":
            return self._generate_bash()
        elif shell_norm == "fish":
            return self._generate_fish()
        else:
            raise ValueError(
                f"Unsupported shell '{shell}'. Supported shells: {', '.join(self.SUPPORTED_SHELLS)}"
            )

    def _generate_zsh(self) -> str:
        return """#compdef bento
# Autogenerated by bento completion zsh

_bento() {
    local -a commands
    commands=(
        'check:Run Clean Architecture AST purity audit'
        'doctor:Run system environment and hygiene diagnostics'
        'export:Export comprehensive Markdown engineering report'
        'arena:Run head-to-head adversarial contract match'
        'orchestra:Run Bento Triad Sprint orchestrator'
        'new:Origami wizard to craft new contracts'
        'run:Execute a single scenario contract file'
        'suite:Execute a directory of benchmark contracts'
        'auto:Run closed-loop agent self-healing'
        'dream:Offline dream cycle pattern analysis'
        'bg:Butler background process daemon manager'
        'memory:Institutional memory bank query and storage'
        'ui:Launch Bento Web Monitor dashboard'
        'monitor:Launch real-time terminal telemetry monitor'
        'completion:Generate shell autocompletions (bash/zsh/fish)'
    )

    if (( CURRENT == 2 )); then
        _describe -t commands 'bento command' commands
    else
        case "$words[2]" in
            run)
                _files -g "*.json"
                ;;
            suite)
                _directories
                ;;
            arena)
                _arguments \\
                    '--challenger[Challenger scenario contract]:file:_files -g "*.json"' \\
                    '--defender[Defender scenario contract]:file:_files -g "*.json"' \\
                    '--metric[Comparison metric]:(pass_rate duration assertions)'
                ;;
            export)
                _arguments '--output[Target file path]:file:_files'
                ;;
            completion)
                _values 'shell' bash zsh fish
                ;;
        esac
    fi
}

_bento "$@"
"""

    def _generate_bash(self) -> str:
        return """# Autogenerated by bento completion bash

_bento_completions() {
    local cur prev words cword
    _init_completion -n = 2>/dev/null || {
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
    }

    local commands="check doctor export arena orchestra new run suite auto dream bg memory ui monitor completion"

    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return 0
    fi

    case "${COMP_WORDS[1]}" in
        run)
            COMPREPLY=( $(compgen -f -X '!*.json' -- "$cur") )
            ;;
        suite)
            COMPREPLY=( $(compgen -d -- "$cur") )
            ;;
        arena)
            if [[ "$prev" == "--challenger" || "$prev" == "--defender" ]]; then
                COMPREPLY=( $(compgen -f -X '!*.json' -- "$cur") )
            elif [[ "$prev" == "--metric" ]]; then
                COMPREPLY=( $(compgen -W "pass_rate duration assertions" -- "$cur") )
            else
                COMPREPLY=( $(compgen -W "--challenger --defender --metric" -- "$cur") )
            fi
            ;;
        export)
            if [[ "$prev" == "--output" ]]; then
                COMPREPLY=( $(compgen -f -- "$cur") )
            else
                COMPREPLY=( $(compgen -W "--output" -- "$cur") )
            fi
            ;;
        completion)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
            ;;
    esac
}

complete -F _bento_completions bento
"""

    def _generate_fish(self) -> str:
        return """# Autogenerated by bento completion fish

complete -c bento -f
complete -c bento -n "__fish_use_subcommand" -a "check" -d "Run Clean Architecture AST purity audit"
complete -c bento -n "__fish_use_subcommand" -a "doctor" -d "Run system environment and hygiene diagnostics"
complete -c bento -n "__fish_use_subcommand" -a "export" -d "Export comprehensive Markdown engineering report"
complete -c bento -n "__fish_use_subcommand" -a "arena" -d "Run head-to-head adversarial contract match"
complete -c bento -n "__fish_use_subcommand" -a "orchestra" -d "Run Bento Triad Sprint orchestrator"
complete -c bento -n "__fish_use_subcommand" -a "new" -d "Origami wizard to craft new contracts"
complete -c bento -n "__fish_use_subcommand" -a "run" -d "Execute a single scenario contract file"
complete -c bento -n "__fish_use_subcommand" -a "suite" -d "Execute a directory of benchmark contracts"
complete -c bento -n "__fish_use_subcommand" -a "auto" -d "Run closed-loop agent self-healing"
complete -c bento -n "__fish_use_subcommand" -a "dream" -d "Offline dream cycle pattern analysis"
complete -c bento -n "__fish_use_subcommand" -a "bg" -d "Butler background process daemon manager"
complete -c bento -n "__fish_use_subcommand" -a "memory" -d "Institutional memory bank query and storage"
complete -c bento -n "__fish_use_subcommand" -a "ui" -d "Launch Bento Web Monitor dashboard"
complete -c bento -n "__fish_use_subcommand" -a "monitor" -d "Launch real-time terminal telemetry monitor"
complete -c bento -n "__fish_use_subcommand" -a "completion" -d "Generate shell autocompletions"

complete -c bento -n "__fish_seen_subcommand_from run" -r -F
complete -c bento -n "__fish_seen_subcommand_from suite" -r -a "(__fish_complete_directories)"
complete -c bento -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"
"""
